[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "Vonvoo"
authors = [{name = "Vonvoo", email = "no@no.com"}]
dynamic = ["version", "description"]

